spring:
  main:
    web-application-type: none
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/mongock4'
  profiles:
    active: mongobee

logging:
  level:
    org:
      springframework:
        data:
          repository:
            config: warn
